In [57]:
# Import Libraries
import numpy as np

# Arrange list using np

a = np.arange(1, 10)
print(a)
print(a.shape)

b = np.arange(1, 10, 2)
print(b)
print(b.shape)

c = np.arange(10, 2, -2)
print(c)
print(c.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
[1 3 5 7 9]
(5,)
[10  8  6  4]
(4,)
