In [61]:
import numpy as np
from scipy.linalg import lu


a = np.mat('1, 2; 3, 4; 5, 6')
print(a)

aT = np.transpose(a)
print(aT)

b = 2*np.eye(3)
print(b)

c = b*a
print(c)

l = lu(a)
print(l)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
[[ 2.  4.]
 [ 6.  8.]
 [10. 12.]]
(array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]]), array([[1. , 0. ],
       [0.2, 1. ],
       [0.6, 0.5]]), array([[5. , 6. ],
       [0. , 0.8]]))
